// <auto-generated />
using BookAPI_DotNet9.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookAPI_DotNet9.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250621064350_Add book data")]
    partial class Addbookdata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookAPI_DotNet9.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearPublished")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "F. Scott Fitzgerald",
                            Title = "The Great Gatsby",
                            YearPublished = 1925
                        },
                        new
                        {
                            Id = 2,
                            Author = "George Orwell",
                            Title = "1984",
                            YearPublished = 1949
                        },
                        new
                        {
                            Id = 3,
                            Author = "Harper Lee",
                            Title = "To Kill a Mockingbird",
                            YearPublished = 1960
                        },
                        new
                        {
                            Id = 4,
                            Author = "Jane Austen",
                            Title = "Pride and Prejudice",
                            YearPublished = 1813
                        },
                        new
                        {
                            Id = 5,
                            Author = "J.D. Salinger",
                            Title = "The Catcher in the Rye",
                            YearPublished = 1951
                        },
                        new
                        {
                            Id = 6,
                            Author = "Herman Melville",
                            Title = "Moby-Dick",
                            YearPublished = 1851
                        },
                        new
                        {
                            Id = 7,
                            Author = "J.R.R. Tolkien",
                            Title = "The Hobbit",
                            YearPublished = 1937
                        },
                        new
                        {
                            Id = 8,
                            Author = "Leo Tolstoy",
                            Title = "War and Peace",
                            YearPublished = 1869
                        },
                        new
                        {
                            Id = 9,
                            Author = "Fyodor Dostoevsky",
                            Title = "Crime and Punishment",
                            YearPublished = 1866
                        },
                        new
                        {
                            Id = 10,
                            Author = "Homer",
                            Title = "The Odyssey",
                            YearPublished = 800
                        },
                        new
                        {
                            Id = 11,
                            Author = "Cormac McCarthy",
                            Title = "The Road",
                            YearPublished = 2006
                        },
                        new
                        {
                            Id = 12,
                            Author = "Aldous Huxley",
                            Title = "Brave New World",
                            YearPublished = 1932
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
